============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 8 items

selenium_ui/confluence_ui.py first driver inits
1604653412196,361,selenium_login:open_login_page,Success,True
1604653413040,759,selenium_login:login_and_view_dashboard,Success,True
1604653413040,1205,selenium_login,Success,True
.test_0_selenium_a_login,Total:1 Passed:1 Failed:0
1604653413799,743,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:2 Passed:2 Failed:0
1604653414790,990,selenium_create_page:open_create_page_editor,Success,True
1604653416093,611,selenium_create_page:save_created_page,Success,True
1604653416093,2293,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:3 Passed:3 Failed:0
1604653418023,1928,selenium_edit_page:open_create_page_editor,Success,True
1604653419243,1200,selenium_edit_page:save_edited_page,Success,True
1604653419243,3148,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:4 Passed:4 Failed:0
1604653420321,633,selenium_create_comment:write_comment,Success,True
1604653420931,610,selenium_create_comment:save_comment,Success,True
1604653420931,1686,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:5 Passed:5 Failed:0
1604653421852,920,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:6 Passed:6 Failed:0
1604653428185,6331,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:7 Passed:7 Failed:0
1604653428370,183,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:8 Passed:8 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 8 passed, 1 warning in 17.67s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 8 items

selenium_ui/confluence_ui.py get driver from global
1604653428626,191,selenium_login:open_login_page,Success,True
1604653430144,1433,selenium_login:login_and_view_dashboard,Success,True
1604653430144,1710,selenium_login,Success,True
.test_0_selenium_a_login,Total:9 Passed:9 Failed:0
1604653430821,663,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:10 Passed:10 Failed:0
1604653431502,679,selenium_create_page:open_create_page_editor,Success,True
1604653433282,636,selenium_create_page:save_created_page,Success,True
1604653433283,2459,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:11 Passed:11 Failed:0
1604653436515,3231,selenium_edit_page:open_create_page_editor,Success,True
1604653437582,1045,selenium_edit_page:save_edited_page,Success,True
1604653437582,4298,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:12 Passed:12 Failed:0
1604653438743,599,selenium_create_comment:write_comment,Success,True
1604653439354,611,selenium_create_comment:save_comment,Success,True
1604653439354,1771,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:13 Passed:13 Failed:0
1604653440433,1077,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:14 Passed:14 Failed:0
1604653450321,9887,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:15 Passed:15 Failed:0
1604653450537,215,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:16 Passed:16 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 8 passed, 1 warning in 22.11s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 8 items

selenium_ui/confluence_ui.py get driver from global
1604653450804,203,selenium_login:open_login_page,Success,True
1604653452351,1462,selenium_login:login_and_view_dashboard,Success,True
1604653452351,1749,selenium_login,Success,True
.test_0_selenium_a_login,Total:17 Passed:17 Failed:0
1604653453153,788,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:18 Passed:18 Failed:0
1604653453917,763,selenium_create_page:open_create_page_editor,Success,True
1604653456836,742,selenium_create_page:save_created_page,Success,True
1604653456836,3681,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:19 Passed:19 Failed:0
1604653460796,3959,selenium_edit_page:open_create_page_editor,Success,True
1604653462243,1426,selenium_edit_page:save_edited_page,Success,True
1604653462243,5406,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:20 Passed:20 Failed:0
1604653464024,1066,selenium_create_comment:write_comment,Success,True
1604653464636,611,selenium_create_comment:save_comment,Success,True
1604653464636,2391,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:21 Passed:21 Failed:0
1604653466490,1852,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:22 Passed:22 Failed:0
1604653483955,17464,selenium_view_dashboard,Success,True
.test_1_selenium_view_dashboard,Total:23 Passed:23 Failed:0
1604653484218,261,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:24 Passed:24 Failed:0


=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 8 passed, 1 warning in 33.63s =========================
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 8 items

selenium_ui/confluence_ui.py get driver from global
1604653484550,277,selenium_login:open_login_page,Success,True
1604653487893,3257,selenium_login:login_and_view_dashboard,Success,True
1604653487893,3620,selenium_login,Success,True
.test_0_selenium_a_login,Total:25 Passed:25 Failed:0
1604653493824,5917,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:26 Passed:26 Failed:0
1604653494866,1040,selenium_create_page:open_create_page_editor,Success,True
1604653500017,1421,selenium_create_page:save_created_page,Success,True
1604653500017,6192,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:27 Passed:27 Failed:0
1604653508012,7993,selenium_edit_page:open_create_page_editor,Success,True
1604653512546,4511,selenium_edit_page:save_edited_page,Success,True
1604653512546,12527,selenium_edit_page,Success,True
.test_1_selenium_edit_page,Total:28 Passed:28 Failed:0
1604653517399,2581,selenium_create_comment:write_comment,Success,True
1604653518012,613,selenium_create_comment:save_comment,Success,True
1604653518013,5465,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:29 Passed:29 Failed:0
1604653531797,13782,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:30 Passed:30 Failed:0
1604653558335,26536,selenium_view_dashboard,Failed measure: selenium_view_dashboard - TimeoutException,False
FAction: test_1_selenium_view_dashboard, Error: confluence_webdriver = <selenium.webdriver.chrome.webdriver.WebDriver (session="e473abf343a9aca5123a5a22f22757a9")>
confluence_datasets = {'blog_id': '25984345', 'blogs': [['8416123', 'CJPDP'], ['8416148', 'PLEB'], ['8416327', 'GSR'], ['8417043', 'CCDI'], ['8418716', 'SOPM'], ['8418929', 'BCBS'], ...], 'custom_pages': [], 'page_id': '981511', ...}
confluence_screen_shots = None

    def test_1_selenium_view_dashboard(confluence_webdriver, confluence_datasets, confluence_screen_shots):
>       modules.view_dashboard(confluence_webdriver, confluence_datasets)

selenium_ui/confluence_ui.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
selenium_ui/confluence/modules.py:81: in view_dashboard
    measure()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @functools.wraps(func)
    def wrapper():
        if LOGIN_ACTION_NAME in interaction:
            globals.login_failed = False
        if globals.login_failed:
            pytest.skip(f"login is failed")
        start = time.time()
        error_msg = 'Success'
        full_exception = ''
        try:
            func()
            success = True
        except Exception:
            success = False
            # https://docs.python.org/2/library/sys.html#sys.exc_info
            exc_type, full_exception = sys.exc_info()[:2]
            error_msg = f"Failed measure: {interaction} - {exc_type.__name__}"
        end = time.time()
        timing = str(int((end - start) * 1000))
    
        with open(selenium_results_file, "a+") as jtl_file:
            timestamp = round(time.time() * 1000)
            jtl_file.write(f"{timestamp},{timing},{interaction},,{error_msg},,{success},0,0,0,0,,0\n")
    
        print(f"{timestamp},{timing},{interaction},{error_msg},{success}")
    
        if not success:
            if LOGIN_ACTION_NAME in interaction:
                globals.login_failed = True
>           raise Exception(error_msg, full_exception)
E           Exception: ('Failed measure: selenium_view_dashboard - TimeoutException', TimeoutException("Error in wait_until: Timed out after 20 sec waiting for <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x7f7f292d59d0>. \nLocator: ('class name', 'update-items')", None, None))

selenium_ui/conftest.py:120: Exception

test_1_selenium_view_dashboard,Total:31 Passed:30 Failed:1
1604653573497,4514,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:32 Passed:31 Failed:1


=================================== FAILURES ===================================
________________________ test_1_selenium_view_dashboard ________________________

confluence_webdriver = <selenium.webdriver.chrome.webdriver.WebDriver (session="e473abf343a9aca5123a5a22f22757a9")>
confluence_datasets = {'blog_id': '25984345', 'blogs': [['8416123', 'CJPDP'], ['8416148', 'PLEB'], ['8416327', 'GSR'], ['8417043', 'CCDI'], ['8418716', 'SOPM'], ['8418929', 'BCBS'], ...], 'custom_pages': [], 'page_id': '981511', ...}
confluence_screen_shots = None

    def test_1_selenium_view_dashboard(confluence_webdriver, confluence_datasets, confluence_screen_shots):
>       modules.view_dashboard(confluence_webdriver, confluence_datasets)

selenium_ui/confluence_ui.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
selenium_ui/confluence/modules.py:81: in view_dashboard
    measure()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @functools.wraps(func)
    def wrapper():
        if LOGIN_ACTION_NAME in interaction:
            globals.login_failed = False
        if globals.login_failed:
            pytest.skip(f"login is failed")
        start = time.time()
        error_msg = 'Success'
        full_exception = ''
        try:
            func()
            success = True
        except Exception:
            success = False
            # https://docs.python.org/2/library/sys.html#sys.exc_info
            exc_type, full_exception = sys.exc_info()[:2]
            error_msg = f"Failed measure: {interaction} - {exc_type.__name__}"
        end = time.time()
        timing = str(int((end - start) * 1000))
    
        with open(selenium_results_file, "a+") as jtl_file:
            timestamp = round(time.time() * 1000)
            jtl_file.write(f"{timestamp},{timing},{interaction},,{error_msg},,{success},0,0,0,0,,0\n")
    
        print(f"{timestamp},{timing},{interaction},{error_msg},{success}")
    
        if not success:
            if LOGIN_ACTION_NAME in interaction:
                globals.login_failed = True
>           raise Exception(error_msg, full_exception)
E           Exception: ('Failed measure: selenium_view_dashboard - TimeoutException', TimeoutException("Error in wait_until: Timed out after 20 sec waiting for <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x7f7f292d59d0>. \nLocator: ('class name', 'update-items')", None, None))

selenium_ui/conftest.py:120: Exception
=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED selenium_ui/confluence_ui.py::test_1_selenium_view_dashboard - Excepti...
============== 1 failed, 7 passed, 1 warning in 89.24s (0:01:29) ===============
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /dc-app-performance-toolkit/app
plugins: apiritif-0.9.5
collected 8 items

selenium_ui/confluence_ui.py get driver from global
1604653576401,2854,selenium_login:open_login_page,Success,True
1604653588338,11853,selenium_login:login_and_view_dashboard,Success,True
1604653588338,14791,selenium_login,Success,True
.test_0_selenium_a_login,Total:33 Passed:32 Failed:1
1604653593553,5200,selenium_view_page,Success,True
.test_1_selenium_view_page,Total:34 Passed:33 Failed:1
1604653603956,10401,selenium_create_page:open_create_page_editor,Success,True
1604653635709,14185,selenium_create_page:save_created_page,Success,True
1604653635709,42154,selenium_create_page,Success,True
.test_1_selenium_create_page,Total:35 Passed:34 Failed:1
1604653663369,27659,selenium_edit_page:open_create_page_editor,Failed measure: selenium_edit_page:open_create_page_editor - TimeoutException,False
1604653663369,27659,selenium_edit_page,Failed measure: selenium_edit_page - Exception,False
FAction: test_1_selenium_edit_page, Error: confluence_webdriver = <selenium.webdriver.chrome.webdriver.WebDriver (session="e473abf343a9aca5123a5a22f22757a9")>
confluence_datasets = {'blog_id': '26334768', 'blogs': [['8416123', 'CJPDP'], ['8416148', 'PLEB'], ['8416327', 'GSR'], ['8417043', 'CCDI'], ['8418716', 'SOPM'], ['8418929', 'BCBS'], ...], 'custom_pages': [], 'page_id': '982729', ...}
confluence_screen_shots = None

    def test_1_selenium_edit_page(confluence_webdriver, confluence_datasets, confluence_screen_shots):
>       modules.edit_confluence_page(confluence_webdriver, confluence_datasets)

selenium_ui/confluence_ui.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
selenium_ui/confluence/modules.py:130: in edit_confluence_page
    measure()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @functools.wraps(func)
    def wrapper():
        if LOGIN_ACTION_NAME in interaction:
            globals.login_failed = False
        if globals.login_failed:
            pytest.skip(f"login is failed")
        start = time.time()
        error_msg = 'Success'
        full_exception = ''
        try:
            func()
            success = True
        except Exception:
            success = False
            # https://docs.python.org/2/library/sys.html#sys.exc_info
            exc_type, full_exception = sys.exc_info()[:2]
            error_msg = f"Failed measure: {interaction} - {exc_type.__name__}"
        end = time.time()
        timing = str(int((end - start) * 1000))
    
        with open(selenium_results_file, "a+") as jtl_file:
            timestamp = round(time.time() * 1000)
            jtl_file.write(f"{timestamp},{timing},{interaction},,{error_msg},,{success},0,0,0,0,,0\n")
    
        print(f"{timestamp},{timing},{interaction},{error_msg},{success}")
    
        if not success:
            if LOGIN_ACTION_NAME in interaction:
                globals.login_failed = True
>           raise Exception(error_msg, full_exception)
E           Exception: ('Failed measure: selenium_edit_page - Exception', Exception('Failed measure: selenium_edit_page:open_create_page_editor - TimeoutException', TimeoutException("Error in wait_until: Timed out after 20 sec waiting for one of the conditions: \n Condition: <selenium.webdriver.support.expected_conditions.text_to_be_present_in_element object at 0x7f7f291fecd0> Locator: ('class name', 'status-indicator-message')\n Condition: <selenium.webdriver.support.expected_conditions.text_to_be_present_in_element object at 0x7f7f291feca0> Locator: ('class name', 'status-indicator-message')\n", None, None)))

selenium_ui/conftest.py:120: Exception

test_1_selenium_edit_page,Total:36 Passed:34 Failed:2
1604653746275,58342,selenium_create_comment:write_comment,Success,True
1604653761030,14754,selenium_create_comment:save_comment,Success,True
1604653761030,79489,selenium_create_comment,Success,True
.test_1_selenium_create_comment,Total:37 Passed:35 Failed:2
1604653771739,10707,selenium_view_blog,Success,True
.test_1_selenium_view_blog,Total:38 Passed:36 Failed:2
1604653811705,39964,selenium_view_dashboard,Failed measure: selenium_view_dashboard - TimeoutException,False
FAction: test_1_selenium_view_dashboard, Error: confluence_webdriver = <selenium.webdriver.chrome.webdriver.WebDriver (session="e473abf343a9aca5123a5a22f22757a9")>
confluence_datasets = {'blog_id': '26334768', 'blogs': [['8416123', 'CJPDP'], ['8416148', 'PLEB'], ['8416327', 'GSR'], ['8417043', 'CCDI'], ['8418716', 'SOPM'], ['8418929', 'BCBS'], ...], 'custom_pages': [], 'page_id': '982729', ...}
confluence_screen_shots = None

    def test_1_selenium_view_dashboard(confluence_webdriver, confluence_datasets, confluence_screen_shots):
>       modules.view_dashboard(confluence_webdriver, confluence_datasets)

selenium_ui/confluence_ui.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
selenium_ui/confluence/modules.py:81: in view_dashboard
    measure()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @functools.wraps(func)
    def wrapper():
        if LOGIN_ACTION_NAME in interaction:
            globals.login_failed = False
        if globals.login_failed:
            pytest.skip(f"login is failed")
        start = time.time()
        error_msg = 'Success'
        full_exception = ''
        try:
            func()
            success = True
        except Exception:
            success = False
            # https://docs.python.org/2/library/sys.html#sys.exc_info
            exc_type, full_exception = sys.exc_info()[:2]
            error_msg = f"Failed measure: {interaction} - {exc_type.__name__}"
        end = time.time()
        timing = str(int((end - start) * 1000))
    
        with open(selenium_results_file, "a+") as jtl_file:
            timestamp = round(time.time() * 1000)
            jtl_file.write(f"{timestamp},{timing},{interaction},,{error_msg},,{success},0,0,0,0,,0\n")
    
        print(f"{timestamp},{timing},{interaction},{error_msg},{success}")
    
        if not success:
            if LOGIN_ACTION_NAME in interaction:
                globals.login_failed = True
>           raise Exception(error_msg, full_exception)
E           Exception: ('Failed measure: selenium_view_dashboard - TimeoutException', TimeoutException("Error in wait_until: Timed out after 20 sec waiting for <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x7f7f291ebf70>. \nLocator: ('class name', 'update-items')", None, None))

selenium_ui/conftest.py:120: Exception

test_1_selenium_view_dashboard,Total:39 Passed:36 Failed:3
1604653825443,3855,selenium_log_out,Success,True
.test_2_selenium_z_log_out,Total:40 Passed:37 Failed:3


=================================== FAILURES ===================================
__________________________ test_1_selenium_edit_page ___________________________

confluence_webdriver = <selenium.webdriver.chrome.webdriver.WebDriver (session="e473abf343a9aca5123a5a22f22757a9")>
confluence_datasets = {'blog_id': '26334768', 'blogs': [['8416123', 'CJPDP'], ['8416148', 'PLEB'], ['8416327', 'GSR'], ['8417043', 'CCDI'], ['8418716', 'SOPM'], ['8418929', 'BCBS'], ...], 'custom_pages': [], 'page_id': '982729', ...}
confluence_screen_shots = None

    def test_1_selenium_edit_page(confluence_webdriver, confluence_datasets, confluence_screen_shots):
>       modules.edit_confluence_page(confluence_webdriver, confluence_datasets)

selenium_ui/confluence_ui.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
selenium_ui/confluence/modules.py:130: in edit_confluence_page
    measure()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @functools.wraps(func)
    def wrapper():
        if LOGIN_ACTION_NAME in interaction:
            globals.login_failed = False
        if globals.login_failed:
            pytest.skip(f"login is failed")
        start = time.time()
        error_msg = 'Success'
        full_exception = ''
        try:
            func()
            success = True
        except Exception:
            success = False
            # https://docs.python.org/2/library/sys.html#sys.exc_info
            exc_type, full_exception = sys.exc_info()[:2]
            error_msg = f"Failed measure: {interaction} - {exc_type.__name__}"
        end = time.time()
        timing = str(int((end - start) * 1000))
    
        with open(selenium_results_file, "a+") as jtl_file:
            timestamp = round(time.time() * 1000)
            jtl_file.write(f"{timestamp},{timing},{interaction},,{error_msg},,{success},0,0,0,0,,0\n")
    
        print(f"{timestamp},{timing},{interaction},{error_msg},{success}")
    
        if not success:
            if LOGIN_ACTION_NAME in interaction:
                globals.login_failed = True
>           raise Exception(error_msg, full_exception)
E           Exception: ('Failed measure: selenium_edit_page - Exception', Exception('Failed measure: selenium_edit_page:open_create_page_editor - TimeoutException', TimeoutException("Error in wait_until: Timed out after 20 sec waiting for one of the conditions: \n Condition: <selenium.webdriver.support.expected_conditions.text_to_be_present_in_element object at 0x7f7f291fecd0> Locator: ('class name', 'status-indicator-message')\n Condition: <selenium.webdriver.support.expected_conditions.text_to_be_present_in_element object at 0x7f7f291feca0> Locator: ('class name', 'status-indicator-message')\n", None, None)))

selenium_ui/conftest.py:120: Exception
________________________ test_1_selenium_view_dashboard ________________________

confluence_webdriver = <selenium.webdriver.chrome.webdriver.WebDriver (session="e473abf343a9aca5123a5a22f22757a9")>
confluence_datasets = {'blog_id': '26334768', 'blogs': [['8416123', 'CJPDP'], ['8416148', 'PLEB'], ['8416327', 'GSR'], ['8417043', 'CCDI'], ['8418716', 'SOPM'], ['8418929', 'BCBS'], ...], 'custom_pages': [], 'page_id': '982729', ...}
confluence_screen_shots = None

    def test_1_selenium_view_dashboard(confluence_webdriver, confluence_datasets, confluence_screen_shots):
>       modules.view_dashboard(confluence_webdriver, confluence_datasets)

selenium_ui/confluence_ui.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
selenium_ui/confluence/modules.py:81: in view_dashboard
    measure()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @functools.wraps(func)
    def wrapper():
        if LOGIN_ACTION_NAME in interaction:
            globals.login_failed = False
        if globals.login_failed:
            pytest.skip(f"login is failed")
        start = time.time()
        error_msg = 'Success'
        full_exception = ''
        try:
            func()
            success = True
        except Exception:
            success = False
            # https://docs.python.org/2/library/sys.html#sys.exc_info
            exc_type, full_exception = sys.exc_info()[:2]
            error_msg = f"Failed measure: {interaction} - {exc_type.__name__}"
        end = time.time()
        timing = str(int((end - start) * 1000))
    
        with open(selenium_results_file, "a+") as jtl_file:
            timestamp = round(time.time() * 1000)
            jtl_file.write(f"{timestamp},{timing},{interaction},,{error_msg},,{success},0,0,0,0,,0\n")
    
        print(f"{timestamp},{timing},{interaction},{error_msg},{success}")
    
        if not success:
            if LOGIN_ACTION_NAME in interaction:
                globals.login_failed = True
>           raise Exception(error_msg, full_exception)
E           Exception: ('Failed measure: selenium_view_dashboard - TimeoutException', TimeoutException("Error in wait_until: Timed out after 20 sec waiting for <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x7f7f291ebf70>. \nLocator: ('class name', 'update-items')", None, None))

selenium_ui/conftest.py:120: Exception
=============================== warnings summary ===============================
../../usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114
  /usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py:1114: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: apiritif
    self._mark_plugins_for_rewrite(hook)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED selenium_ui/confluence_ui.py::test_1_selenium_edit_page - Exception: (...
FAILED selenium_ui/confluence_ui.py::test_1_selenium_view_dashboard - Excepti...
============== 2 failed, 6 passed, 1 warning in 251.91s (0:04:11) ==============
