[2020-12-17 17:09:24,789 INFO root] Taurus CLI Tool v1.15.0
[2020-12-17 17:09:24,789 DEBUG root] Command-line options: {'log': '/tmp/bzt_evvvj0ja.log', 'option': ['modules.console.disable=true'], 'quiet': None, 'verbose': None, 'no_system_configs': None, 'aliases': []}
[2020-12-17 17:09:24,789 DEBUG root] Python: CPython 3.8.0
[2020-12-17 17:09:24,789 DEBUG root] OS: uname_result(system='Linux', node='ea75a4485b5f', release='5.4.0-1029-aws', version='#30~18.04.1-Ubuntu SMP Tue Oct 20 11:09:25 UTC 2020', machine='x86_64', processor='x86_64')
[2020-12-17 17:09:24,789 INFO root] Starting with configs: ['bitbucket.yml']
[2020-12-17 17:09:24,790 DEBUG root] Using personal config: /root/.bzt-rc
[2020-12-17 17:09:24,790 INFO Engine] Configuring...
[2020-12-17 17:09:24,791 DEBUG Engine] Reading system configs from: /etc/bzt.d
[2020-12-17 17:09:24,840 DEBUG Engine] Base configs list: ['/usr/local/lib/python3.8/dist-packages/bzt/resources/10-base-config.yml', '/etc/bzt.d/50-pbench-enhanced.json', '/etc/bzt.d/90-artifacts-dir.json', '/etc/bzt.d/99-zinstallID.json']
[2020-12-17 17:09:24,840 DEBUG Engine.Configuration] Configs: ['/usr/local/lib/python3.8/dist-packages/bzt/resources/10-base-config.yml', '/etc/bzt.d/50-pbench-enhanced.json', '/etc/bzt.d/90-artifacts-dir.json', '/etc/bzt.d/99-zinstallID.json']
[2020-12-17 17:09:24,841 DEBUG Engine.Configuration] Reading /usr/local/lib/python3.8/dist-packages/bzt/resources/10-base-config.yml as YAML
[2020-12-17 17:09:24,856 DEBUG Engine.Configuration] Reading /etc/bzt.d/50-pbench-enhanced.json as YAML
[2020-12-17 17:09:24,857 DEBUG Engine.Configuration] Reading /etc/bzt.d/90-artifacts-dir.json as YAML
[2020-12-17 17:09:24,858 DEBUG Engine.Configuration] Reading /etc/bzt.d/99-zinstallID.json as YAML
[2020-12-17 17:09:24,858 DEBUG Engine] User configs list: ['/root/.bzt-rc', 'bitbucket.yml']
[2020-12-17 17:09:24,858 DEBUG Engine.Configuration] Configs: ['/root/.bzt-rc', 'bitbucket.yml']
[2020-12-17 17:09:24,859 DEBUG Engine.Configuration] Reading /root/.bzt-rc as YAML
[2020-12-17 17:09:24,861 DEBUG Engine.Configuration] Reading bitbucket.yml as YAML
[2020-12-17 17:09:24,869 DEBUG Engine.Configuration] Configs: ['/root/.bzt-rc', 'bitbucket.yml']
[2020-12-17 17:09:24,869 DEBUG Engine.Configuration] Reading /root/.bzt-rc as YAML
[2020-12-17 17:09:24,872 DEBUG Engine.Configuration] Reading bitbucket.yml as YAML
[2020-12-17 17:09:24,905 DEBUG Engine] Requesting updates info: https://gettaurus.org/updates/?version=1.15.0&installID=Docker
[2020-12-17 17:09:24,905 DEBUG ConfigOverrider] Applying modules.console.disable=true
[2020-12-17 17:09:24,905 DEBUG HTTPClient] Making HTTP request GET https://gettaurus.org/updates/?version=1.15.0&installID=Docker
[2020-12-17 17:09:24,905 DEBUG ConfigOverrider] Applying: [disable]=true
[2020-12-17 17:09:24,906 DEBUG ConfigOverrider] Parsed override value: 'true' -> True (<class 'bool'>)
[2020-12-17 17:09:24,906 INFO Engine] Artifacts dir: /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24
[2020-12-17 17:09:24,908 DEBUG Engine] New artifact filename: /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/effective
[2020-12-17 17:09:24,909 DEBUG urllib3.connectionpool] Starting new HTTPS connection (1): gettaurus.org:443
[2020-12-17 17:09:24,909 DEBUG Engine.Configuration] Dumping YAML config into /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/effective.yml
[2020-12-17 17:09:24,922 DEBUG Engine.Configuration] Dumping JSON config into /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/effective.json
[2020-12-17 17:09:24,923 DEBUG Engine] New artifact filename: /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/merged.yml
[2020-12-17 17:09:24,923 DEBUG Engine.Configuration] Dumping YAML config into /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/merged.yml
[2020-12-17 17:09:24,927 DEBUG Engine] New artifact filename: /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/merged.json
[2020-12-17 17:09:24,928 DEBUG Engine.Configuration] Dumping JSON config into /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/merged.json
[2020-12-17 17:09:24,928 DEBUG Engine] Add existing artifact (move=False): bitbucket.yml
[2020-12-17 17:09:24,928 DEBUG Engine] Copying bitbucket.yml to /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/bitbucket.yml
[2020-12-17 17:09:24,928 DEBUG Engine] Set PYTHONPATH to '/root/.bzt/python-packages/3.8.0' + '/dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/python-packages/3.8.0' + 
[2020-12-17 17:09:24,929 DEBUG Engine] Content of user packages dir: %s
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: application_hostname=bitbucket-loadbala-cs8s8ccqbfud-30797893.us-west-1.elb.amazonaws.com
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: application_protocol=http
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: application_port=80
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: secure=True
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: admin_login=admin
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: admin_password=admin
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: load_executor=jmeter
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: concurrency=20
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: test_duration=50m
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: ramp-up=10m
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: total_actions_per_hour=32700
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: WEBDRIVER_VISIBLE=False
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: JMETER_VERSION=5.2.1
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: LANGUAGE=en_US.utf8
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: allow_analytics=True
[2020-12-17 17:09:24,930 DEBUG Engine] OS env: TAURUS_ARTIFACTS_DIR=/dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24
[2020-12-17 17:09:24,930 DEBUG root] Closing log handler: /tmp/bzt_evvvj0ja.log
[2020-12-17 17:09:24,930 DEBUG root] Switched writing logs to /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/bzt.log
[2020-12-17 17:09:24,930 DEBUG root] Linting config
[2020-12-17 17:09:24,932 INFO Engine] Preparing...
[2020-12-17 17:09:24,933 DEBUG Engine] Module config: consolidator {'class': 'bzt.modules.aggregator.ConsolidatingAggregator', 'rtimes-len': 0, 'percentiles': []}
[2020-12-17 17:09:24,933 DEBUG root] Importing module: bzt.modules.aggregator
[2020-12-17 17:09:25,183 DEBUG root] Loading class: 'ConsolidatingAggregator' from <module 'bzt.modules.aggregator' from '/usr/local/lib/python3.8/dist-packages/bzt/modules/aggregator.py'>
[2020-12-17 17:09:25,183 DEBUG Engine.consolidator] Buffer scaling setup: percentile None from [] selected
[2020-12-17 17:09:25,183 DEBUG Engine] Module config: monitoring {'class': 'bzt.modules.monitoring.Monitoring'}
[2020-12-17 17:09:25,183 DEBUG root] Importing module: bzt.modules.monitoring
[2020-12-17 17:09:25,186 DEBUG root] Loading class: 'Monitoring' from <module 'bzt.modules.monitoring' from '/usr/local/lib/python3.8/dist-packages/bzt/modules/monitoring.py'>
[2020-12-17 17:09:25,186 DEBUG Engine] Module config: shellexec {'class': 'bzt.modules.shellexec.ShellExecutor'}
[2020-12-17 17:09:25,186 DEBUG root] Importing module: bzt.modules.shellexec
[2020-12-17 17:09:25,201 DEBUG easyprocess] version=0.3
[2020-12-17 17:09:25,203 DEBUG pyvirtualdisplay] version=1.3.2
[2020-12-17 17:09:25,239 DEBUG root] Loading class: 'ShellExecutor' from <module 'bzt.modules.shellexec' from '/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py'>
[2020-12-17 17:09:25,239 DEBUG Engine.shellexec] Added prepare task: {'command': 'python util/pre_run/environment_checker.py'}
[2020-12-17 17:09:25,239 DEBUG Engine.shellexec] Added prepare task: {'command': 'python util/pre_run/git_client_check.py'}
[2020-12-17 17:09:25,239 DEBUG Engine.shellexec] Added prepare task: {'command': 'python util/data_preparation/bitbucket_prepare_data.py'}
[2020-12-17 17:09:25,239 DEBUG Engine.shellexec] Added shutdown task: {'command': 'python util/post_run/jmeter_post_check.py'}
[2020-12-17 17:09:25,239 DEBUG Engine.shellexec] Added shutdown task: {'command': 'python util/jtl_convertor/jtls-to-csv.py kpi.jtl selenium.jtl'}
[2020-12-17 17:09:25,239 DEBUG Engine.shellexec] Added post-process task: {'command': 'python util/analytics/analytics.py bitbucket'}
[2020-12-17 17:09:25,239 DEBUG Engine.shellexec] Added post-process task: {'command': 'python util/post_run/cleanup_results_dir.py'}
[2020-12-17 17:09:25,239 INFO Engine.shellexec.Task] Starting shell command: python util/pre_run/environment_checker.py
[2020-12-17 17:09:25,240 DEBUG root] Executing shell: python util/pre_run/environment_checker.py at /dc-app-performance-toolkit/app
[2020-12-17 17:09:25,332 DEBUG Engine.shellexec.Task] Output for python util/pre_run/environment_checker.py:
Python version: (3, 8, 0)
Data Center App Performance Toolkit version: 3.2.0

[2020-12-17 17:09:25,332 DEBUG Engine.shellexec.Task] Task was finished with exit code 0: python util/pre_run/environment_checker.py
[2020-12-17 17:09:25,332 INFO Engine.shellexec.Task] Starting shell command: python util/pre_run/git_client_check.py
[2020-12-17 17:09:25,333 DEBUG root] Executing shell: python util/pre_run/git_client_check.py at /dc-app-performance-toolkit/app
[2020-12-17 17:09:25,376 DEBUG Engine.shellexec.Task] Output for python util/pre_run/git_client_check.py:
Git version: b'git version 2.17.1\n'

[2020-12-17 17:09:25,376 DEBUG Engine.shellexec.Task] Task was finished with exit code 0: python util/pre_run/git_client_check.py
[2020-12-17 17:09:25,376 INFO Engine.shellexec.Task] Starting shell command: python util/data_preparation/bitbucket_prepare_data.py
[2020-12-17 17:09:25,377 DEBUG root] Executing shell: python util/data_preparation/bitbucket_prepare_data.py at /dc-app-performance-toolkit/app
[2020-12-17 17:09:25,590 DEBUG urllib3.connectionpool] https://gettaurus.org:443 "GET /updates/?version=1.15.0&installID=Docker HTTP/1.1" 200 39
[2020-12-17 17:09:25,591 DEBUG Engine] Taurus updates info: {'latest': '1.15.1', 'needsUpgrade': True}
[2020-12-17 17:09:25,591 WARNING Engine] There is newer version of Taurus 1.15.1 available, consider upgrading. What's new: http://gettaurus.org/docs/Changelog/
[2020-12-17 17:09:55,602 DEBUG Engine.shellexec.Task] Output for python util/data_preparation/bitbucket_prepare_data.py:
Started preparing data
Server url:  http://bitbucket-loadbala-cs8s8ccqbfud-30797893.us-west-1.elb.amazonaws.com:80

[2020-12-17 17:09:55,602 WARNING Engine.shellexec.Task] Errors for python util/data_preparation/bitbucket_prepare_data.py:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='bitbucket-loadbala-cs8s8ccqbfud-30797893.us-west-1.elb.amazonaws.com', port=80): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "util/data_preparation/bitbucket_prepare_data.py", line 164, in <module>
    main()
  File "util/data_preparation/bitbucket_prepare_data.py", line 154, in main
    __check_current_language(client)
  File "util/data_preparation/bitbucket_prepare_data.py", line 136, in __check_current_language
    language = bitbucket_api.get_locale()
  File "/dc-app-performance-toolkit/app/util/api/bitbucket_clients.py", line 167, in get_locale
    page = self.get(f'{self.host}/dashboard', "Could not get page content.").content
  File "/dc-app-performance-toolkit/app/util/api/abstract_clients.py", line 61, in get
    response = self.session.get(url, auth=self.base_auth, verify=False, timeout=self.requests_timeout,
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='bitbucket-loadbala-cs8s8ccqbfud-30797893.us-west-1.elb.amazonaws.com', port=80): Read timed out. (read timeout=30)

[2020-12-17 17:09:55,602 DEBUG Engine.shellexec.Task] Task was finished with exit code 1: python util/data_preparation/bitbucket_prepare_data.py
[2020-12-17 17:09:55,605 ERROR root] CalledProcessError: Command 'python util/data_preparation/bitbucket_prepare_data.py' returned non-zero exit status 1.
  File "/usr/local/lib/python3.8/dist-packages/bzt/cli.py", line 259, in perform
    self.engine.prepare()
  File "/usr/local/lib/python3.8/dist-packages/bzt/engine/engine.py", line 215, in prepare
    self.__prepare_services()
  File "/usr/local/lib/python3.8/dist-packages/bzt/engine/engine.py", line 668, in __prepare_services
    module.prepare()
  File "/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py", line 130, in prepare
    task.start()
  File "/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py", line 217, in start
    self._get_results()
  File "/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py", line 244, in _get_results
    raise CalledProcessError(self.process.returncode, self)
[2020-12-17 17:09:55,605 INFO Engine] Post-processing...
[2020-12-17 17:09:55,606 DEBUG Engine.consolidator] Consolidator buffer[0]: dict_keys([])
[2020-12-17 17:09:55,606 INFO Engine.shellexec.Task] Starting shell command: python util/analytics/analytics.py bitbucket
[2020-12-17 17:09:55,606 DEBUG root] Executing shell: python util/analytics/analytics.py bitbucket at /dc-app-performance-toolkit/app
[2020-12-17 17:09:55,804 WARNING Engine.shellexec.Task] Errors for python util/analytics/analytics.py bitbucket:
Traceback (most recent call last):
  File "util/analytics/analytics.py", line 144, in <module>
    main()
  File "util/analytics/analytics.py", line 137, in main
    collector = AnalyticsCollector(application)
  File "util/analytics/analytics.py", line 33, in __init__
    self.results_log = ResultsFileReader()
  File "/dc-app-performance-toolkit/app/util/analytics/log_reader.py", line 120, in __init__
    self.results_log = self.get_results_log()
  File "/dc-app-performance-toolkit/app/util/analytics/log_reader.py", line 124, in get_results_log
    self.validate_file_exists(results_log_path)
  File "/dc-app-performance-toolkit/app/util/analytics/log_reader.py", line 16, in validate_file_exists
    raise Exception(f'{path} does not exist')
Exception: /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/results.csv does not exist

[2020-12-17 17:09:55,805 DEBUG Engine.shellexec.Task] Task was finished with exit code 1: python util/analytics/analytics.py bitbucket
[2020-12-17 17:09:55,805 DEBUG Engine] post_process: Command 'python util/analytics/analytics.py bitbucket' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bzt/engine/engine.py", line 340, in post_process
    module.post_process()
  File "/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py", line 159, in post_process
    task.start()
  File "/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py", line 217, in start
    self._get_results()
  File "/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py", line 244, in _get_results
    raise CalledProcessError(self.process.returncode, self)
subprocess.CalledProcessError: Command 'python util/analytics/analytics.py bitbucket' returned non-zero exit status 1.

[2020-12-17 17:09:55,806 DEBUG Engine.Configuration] Dumping YAML config into /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/effective.yml
[2020-12-17 17:09:55,821 DEBUG Engine.Configuration] Dumping JSON config into /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/effective.json
[2020-12-17 17:09:55,824 DEBUG root] CalledProcessError: Command 'python util/analytics/analytics.py bitbucket' returned non-zero exit status 1.
  File "/usr/local/lib/python3.8/dist-packages/bzt/cli.py", line 267, in perform
    self.engine.post_process()
  File "/usr/local/lib/python3.8/dist-packages/bzt/engine/engine.py", line 354, in post_process
    reraise(exc_info, exc_value)
  File "/usr/local/lib/python3.8/dist-packages/bzt/utils.py", line 102, in reraise
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/bzt/engine/engine.py", line 340, in post_process
    module.post_process()
  File "/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py", line 159, in post_process
    task.start()
  File "/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py", line 217, in start
    self._get_results()
  File "/usr/local/lib/python3.8/dist-packages/bzt/modules/shellexec.py", line 244, in _get_results
    raise CalledProcessError(self.process.returncode, self)
[2020-12-17 17:09:55,824 INFO root] Artifacts dir: /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24
[2020-12-17 17:09:55,824 WARNING root] Done performing with code: 1
[2020-12-17 17:09:55,824 DEBUG root] Closing log handler: /dc-app-performance-toolkit/app/results/bitbucket/2020-12-17_17-09-24/bzt.log
